#!/bin/sh
# A dmenu wrapper script for system functions.
case "$(readlink -f /sbin/init)" in
	*systemd*) ctl='systemctl' ;;
	*) ctl='loginctl' ;;
esac

case "$(printf "🔒 Lock Screen?\nExit WM?\nRestart WM?\nHibernate?\nReboot?\nShut off?\nSleep?\nShut down display?" | dmenu -c -p 'DWM: ')" in
	'🔒 lock') slock ;;
	'🚪 leave dwm') kill -TERM "$(pgrep -u "$USER" "\bdwm$")" ;;
	'♻️ renew dwm') kill -HUP "$(pgrep -u "$USER" "\bdwm$")" ;;
	'🐻 hibernate') slock $ctl hibernate ;;
	'💤 sleep') slock $ctl suspend ;;
	'🔃 reboot') $ctl reboot -i ;;
	'🖥️shutdown') $ctl poweroff -i ;;
	'📺 display off') xset dpms force off ;;
	*) exit 1 ;;
esac
